### ISSUE TITLE
Wi-Fiつながらない？

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/01-Spica-hw#1]
Wi-Fi処理書いても動かないらしい
@y-ogawara

**Comment by multiverse2011** [comment]
考えられるのは
- リセット回路を組んでいない
https://ehbtj.com/electronics/instability-measures-for-esp8266/

![image](https://user-images.githubusercontent.com/12444722/40366439-17bb7a80-5e12-11e8-99fd-9b7884dd2834.png)

- GND配線が不足
内部的につながっているが実際につないでおかないと不安定になるらしい。
https://plaza.rakuten.co.jp/aisuke37/diary/201702240001/

- 電源ICの問題
負荷過渡応答特性に優れていない？要は突入電流で死亡してる説。これに関しては昇圧回路組んでるので濃厚な感じはする
https://ehbtj.com/electronics/instability-measures-for-esp8266/

**Comment by multiverse2011** [comment]
上記問題点のGNDの配線のみで解決はしました。

**Comment by multiverse2011** [comment]
で、少々問題があって電池駆動時に高負荷になると落ちます。
おそらく電流が不足していると思われるので昇圧ICをもうちょいアンペアが出るやつにする必要があるかと

**Comment by y-ogawara** [comment]
昇圧ICの値段上がりすぎるようだったら、ESP32用の電池用意するパターンもあるね

**Comment by multiverse2011** [comment]
ESP32用の電池というかICの許容電流の話ですね

**Comment by y-ogawara** [comment]
勘違いだったー:innocent:

**Comment by multiverse2011** [comment]
いったんWi-Fiつながらないわけではないので別issue立てました。 #3
