### ISSUE TITLE
commandBlock読み取り

### ISSUE THREAD

**Issue by y-ogawara** [t-robop/01-Spica-hw#16]
udp受信したデータを、modelに突っ込む done
modelを展開して、それぞれの処理をする
(if,for,breakはむずい)

**Comment by y-ogawara** [comment]
if,forはたぶん終わった。

breakだけ？ @Dai1678

**Comment by Dai1678** [comment]
forの解釈関数実装して、整形まで完了した
ifはこれからまたデバッグする

breakはまだ。
