### ISSUE TITLE
電流が足りなくてResetされる

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/01-Spica-hw#3]
3.3Vの昇圧ICがいまのICだと電流が足りなくなって落ちることがある

**Comment by multiverse2011** [comment]
個人的な見解ですが
過電流になり電圧降下する→CPUのクロックが大幅ダウン→Wi-Fi関連の通信をさばけなくなる→loop出回っている中にあるシリアルモニタも動かなくなる→Resetがかかる
という流れだと思う

**Comment by y-ogawara** [comment]
ESP32のパワーを押さえる方向性も考えたい、ArduinoCoreで出来るのか解ってないけど

**Comment by multiverse2011** [comment]
http://d.hatena.ne.jp/wakwak_koba/20170228#p1

どうも40MHzモードなるものでコンパイルするとまともに動くらしい？？

**Comment by y-ogawara** [comment]
やっぱりか、でも設定毎回変えるのは忘れそうだなぁ・・・

**Comment by multiverse2011** [comment]
電圧下がって勝手に再起動しちゃうのを防ぐしかない

**Comment by y-ogawara** [comment]
https://strawberry-linux.com/support/12291/1684689
これ300mA行けるっぽいな

**Comment by multiverse2011** [comment]
![image](https://user-images.githubusercontent.com/12444722/40429590-01035822-5ede-11e8-8855-2b5a44763650.png)

https://www.mgo-tec.com/blog-entry-esp-wroom-32-current.html/2

電流結構いりますね〜 :innocent:

**Comment by y-ogawara** [comment]
ちなみに今日やった検証って秋月で買ったやつでやってる？

**Comment by y-ogawara** [comment]
@multiverse2011 これ結局pin配置変えたら治ったやつだよね？間違ってなかったらcloseしといてー
