### ISSUE TITLE
ESPのリブート中にキャンセル処理を送るとクラッシュする

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-hw#39]
PCからESPにプログラムをアップロードした直後の状態に対して、タブレットから何回もUDP送信してもESP側がパケットを受信していない

ESP本体のリセットボタンを押してリブートさせると高確率で回復する

**Comment by multiverse2011** [comment]
https://github.com/t-robop/01-Spica-hw/issues/44
こっちと統合

**Comment by multiverse2011** [comment]
ESPのバージョンを戻して検証する必要あり
